# Generated by Django 5.2.2 on 2026-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fame', '0001_initial'),
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworkusers',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='community_members', to='fame.expertiseareas'),
        ),
    ]
